services:
  postgres:
    image: postgres:16-alpine
    container_name: makanbang-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: makanbang
      POSTGRES_PASSWORD: makanbang
      POSTGRES_DB: makanbang
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
